image: jaymoulin/youtube-music-uploader:$FULLVERSION
manifests:
  -
    image: jaymoulin/youtube-music-uploader:$VERSION-arm32v6
    platform:
      architecture: arm
      variant: v6
      os: linux
  -
    image: jaymoulin/youtube-music-uploader:$VERSION-arm64v8
    platform:
      architecture: arm64
      os: linux
  -
    image: jaymoulin/youtube-music-uploader:$VERSION-amd64
    platform:
      architecture: amd64
      os: linux
  -
    image: jaymoulin/youtube-music-uploader:$VERSION-i386
    platform:
      architecture: 386
      os: linux
